"""added a few default values

Revision ID: 0e49c21b21ef
Revises: 9b5d5cc42db3
Create Date: 2025-10-07 20:00:05.882185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e49c21b21ef'
down_revision: Union[str, None] = '9b5d5cc42db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_validated', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_validated')
    # ### end Alembic commands ###