"""fix photos unique

Revision ID: f5ab0f66889a
Revises: d6fa8876ad9c
Create Date: 2026-03-15 10:52:04.740064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ab0f66889a'
down_revision: Union[str, None] = 'd6fa8876ad9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=True)
    # ### end Alembic commands ###